### PR TITLE
feat: create Quality Inspections from account and stock documents

### PR DESCRIPTION
**Pull request by Alchez**
quality-inspection

### CODE REVIEW

**Comment by vjFaLk** [comment]
Task linked: [CU-r76myq QUESTION: Can't get access to "Quality Inspection"](https://app.clickup.com/t/r76myq)

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/erpnext/pull/25221).

**Comment by vjFaLk** [comment]
@Alchez you only make QI when you either receive something or manufacture it. Doesn't make sense to put it *everywhere*. Maybe limit it to just Purchase Receipt for now. Also Manufacturing has it's own...quality thing (I think).

**Comment by Alchez** [comment]
@vjFaLk, it'll only show up on 4 doctypes right now - Purchase Invoice, Purchase Receipt, Sales Invoice and Delivery Note. All 4 of these doctypes have the Quality Inspection field.

For the invoice documents, QI comes into play if you're using the "Update Stock" flag.

**Pull request merged**
