### PR TITLE
fix: improve bom autoname logic [CU-2b3cgqz]

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Task linked: [CU-2b3cgqz DataError: (1406, "Data too long for column 'parent' at row 1")](https://app.clickup.com/t/2b3cgqz)

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/erpnext/pull/29815)

**Comment by vjFaLk** [comment]
@Alchez should we make this to v13 as well?

**Comment by Alchez** [comment]
@vjFaLk they did merge this into [v13](https://github.com/frappe/erpnext/pull/30194) as well actually. This is already in [our fork](https://github.com/ParsimonyGit/erpnext/blob/parsimony-production-v13/erpnext/manufacturing/doctype/bom/bom.py) too.

**Pull request merged**
