### PR TITLE
fix: restore Plaid's enqueue function

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Task linked: [CU-jd2hu0 Plaid error: 'enqueue_synchronization' is not defined](https://app.clickup.com/t/jd2hu0)

**Comment by vjFaLk** [comment]
@Alchez can you confirm that this is the only thing that got accidentally deleted?

**Comment by Alchez** [comment]
@vjFaLk, the only other thing I see is a `FETCH_HEAD` file in the root folder of the app, but everything else seems fine

**Comment by vjFaLk** [comment]
@Alchez How did that get there?

**Comment by Alchez** [comment]
Not sure, but it seems to have arrived in that merge commit

**Pull request merged**
